// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTE869MiuOsitUcHmict75CZA1Sp0hsEk',
    appId: '1:545884750946:web:2d01d5facc035dd1aa7d3b',
    messagingSenderId: '545884750946',
    projectId: 'storyteller-102c5',
    authDomain: 'storyteller-102c5.firebaseapp.com',
    storageBucket: 'storyteller-102c5.firebasestorage.app',
    measurementId: 'G-NQDKL4X6YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATsy5-GcUwDkxKRA6indzgkFfAEIm0uCY',
    appId: '1:545884750946:android:ca515b1d4d2898abaa7d3b',
    messagingSenderId: '545884750946',
    projectId: 'storyteller-102c5',
    storageBucket: 'storyteller-102c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2h1NsHQRV0dl1MGN6zuQ3eXvnIdAoAPo',
    appId: '1:545884750946:ios:e8b650c59721dddaaa7d3b',
    messagingSenderId: '545884750946',
    projectId: 'storyteller-102c5',
    storageBucket: 'storyteller-102c5.firebasestorage.app',
    iosBundleId: 'com.example.adminStoryteller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2h1NsHQRV0dl1MGN6zuQ3eXvnIdAoAPo',
    appId: '1:545884750946:ios:e8b650c59721dddaaa7d3b',
    messagingSenderId: '545884750946',
    projectId: 'storyteller-102c5',
    storageBucket: 'storyteller-102c5.firebasestorage.app',
    iosBundleId: 'com.example.adminStoryteller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTE869MiuOsitUcHmict75CZA1Sp0hsEk',
    appId: '1:545884750946:web:59d5c9e6f0d16ba4aa7d3b',
    messagingSenderId: '545884750946',
    projectId: 'storyteller-102c5',
    authDomain: 'storyteller-102c5.firebaseapp.com',
    storageBucket: 'storyteller-102c5.firebasestorage.app',
    measurementId: 'G-M1F8BNP551',
  );

}